{% set version = "1.24.0.125_g9a220d25" %}

package:
  name: crosstool-ng
  version: {{ version }}

source:
  git_url: https://github.com/conda-forge/crosstool-ng.git
  git_tag: {{ version.split("_")[-1][1:] }}
  patches:
    - verbosity.patch

build:
  number: 0
  skip: True  # [not linux]
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    # TODO We need some [not bootstrapping] selector or something?
    - {{ compiler('c') }}
    - autoconf
    - automake
    - texinfo
    - bison
    - flex
    - gettext
    - git
    - help2man
    - make
    - texinfo
    - unzip
    - wget
  host:
    - ncurses
    - libtool
    - flex
    - bison
  run:
    - ncurses
    - libtool

test:
  commands:
    - ct-ng -h
    - test -f $PREFIX/share/crosstool-ng/config/versions/linux.in

about:
  home: http://crosstool-ng.org/
  license: GPL-2.0-or-later
  license_file:
    - COPYING
    - licenses.d/gpl.txt
    - licenses.d/lgpl.txt
    - licenses.d/by-sa/deed.en
    - licenses.d/by-sa/legalcode
  summary: A versatile (cross-)toolchain generator.
  dev_url: https://github.com/crosstool-ng/crosstool-ng

extra:
  recipe-maintainers:
    - isuruf
