{% set version = "1.23.0.452_gd1585345" %}

package:
  name: crosstool-ng
  version: {{ version }}

source:
  git_url: https://github.com/continuumio/crosstool-ng.git
  git_tag: {{ version.split("_")[-1][1:] }}

build:
  number: 2
  skip: True  # [not linux]
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    # TODO We need some [not bootstrapping] selector or something?
    - {{ compiler('c') }}
    - autoconf
    - automake
    - texinfo
    - bison
    - flex
    - gettext
    - git
    - help2man
    - make
    - texinfo
    - unzip
    - wget
  host:
    - ncurses
    - libtool
  run:
    - ncurses
    - libtool

test:
  commands:
    - ct-ng -h

about:
  home: http://crosstool-ng.org/
  license: GPL-2.0
  license_file:
    - COPYING
    - licenses.d/gpl.txt
    - licenses.d/lgpl.txt
    - licenses.d/by-sa/deed.en
    - licenses.d/by-sa/legalcode
  summary: A versatile (cross-)toolchain generator.
  dev_url: https://github.com/crosstool-ng/crosstool-ng

extra:
  recipe-maintainers:
    - isuruf
